export const FETCH_ALL_COMPANIES = "FETCH_ALL_COMPANIES"
export const FETCH_ALL_COMPANIES_ERROR = "FETCH_ALL_COMPANIES_ERROR"
export const JOB_STATE_UPDATED = "JOB_STATE_UPDATED"
export const JOB_STATE_UPDATED_ERROR = "JOB_STATE_UPDATED_ERROR"
export const JOB_STATES_UPDATED = "JOB_STATES_UPDATED"
export const JOB_STATES_UPDATED_ERROR = "JOB_STATES_UPDATED_ERROR"
export const JOB_POSTING_ADDED_ERROR = "JOB_POSTING_ADDED_ERROR"
export const JOB_POSTING_ADDED = "JOB_POSTING_ADDED"

