export const FETCH_ALL_COMPANIES = "FETCH_ALL_COMPANIES";
export const FETCH_ALL_COMPANIES_ERROR = "FETCH_ALL_COMPANIES_ERROR";
export const JOB_STATE_UPDATED = "JOB_STATE_UPDATED";
export const JOB_STATE_UPDATED_ERROR = "JOB_STATE_UPDATED_ERROR";
export const JOB_STATES_UPDATED = "JOB_STATES_UPDATED";
export const JOB_STATES_UPDATED_ERROR = "JOB_STATES_UPDATED_ERROR";
export const UPDATE_SEARCH_FILTERS = "UPDATE_SEARCH_FILTERS";
export const BLACKLIST_COMPANY = "BLACKLIST_COMPANY";
export const BLACKLIST_COMPANY_ERROR = "BLACKLIST_COMPANY_ERROR";
export const FETCH_BLACKLISTED_COMPANIES = "FETCH_BLACKLISTED_COMPANIES";

